base_model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 10

quantization_schemes:
  - type: "uniform"
    params:
      num_bins: 10
  - type: "quantile"
    params:
      num_quantiles: 10

aed_models:
  - type: "RandomForestClassifier"
    params:
      n_estimators: 50
      max_depth: 5
  - type: "GradientBoostingClassifier"
    params:
      n_estimators: 50
      max_depth: 3

threshold_model:
  type: "LogisticRegression"
  params:
    C: 1.0