data:
  categorical_columns:
    - column1
    - column2
  numerical_columns:
    - column3
    - column4

base_model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 10

quantization_schemes:
  - type: "adaptive"
    params:
      n_bins: 10
      encode: "ordinal"
      strategy: "uniform"
  - type: "adaptive"
    params:
      n_bins: 20
      encode: "ordinal"
      strategy: "quantile"

aed_models:
  - type: "RandomForestClassifier"
    params:
      n_estimators: 50
      max_depth: 5
  - type: "GradientBoostingClassifier"
    params:
      n_estimators: 50
      max_depth: 3

threshold_model:
  type: "LogisticRegression"
  params:
    C: 1.0