aed_models:
- params:
    max_depth: 5
    n_estimators: 50
  type: RandomForestClassifier
- params:
    max_depth: 3
    n_estimators: 50
  type: GradientBoostingClassifier
base_model:
  params:
    max_depth: 10
    n_estimators: 100
  type: RandomForestClassifier
categorical_columns:
- feature_0
- feature_1
- feature_2
- feature_3
- feature_4
numerical_columns:
- feature_5
- feature_6
- feature_7
- feature_8
- feature_9
- feature_10
- feature_11
- feature_12
- feature_13
- feature_14
- feature_15
- feature_16
- feature_17
- feature_18
- feature_19
quantization_schemes:
- params:
    encode: ordinal
    n_bins: 10
    strategy: uniform
  type: adaptive
- params:
    encode: ordinal
    n_bins: 20
    strategy: quantile
  type: adaptive
target_column: target
threshold_model:
  params:
    C: 1.0
  type: LogisticRegression
